name: my_note
description: "A simple app for secure notes"
publish_to: "none"

version: 1.2.2
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Encryption
  encrypt: ^5.0.3
  crypto: ^3.0.3
  # UI & Utility
  cupertino_icons: ^1.0.3
  # FIX: Update intl to satisfy flutter_quill's dependency requirement (0.20.2)
  intl: ^0.20.2
  flutter_colorpicker: ^1.0.3

  # Rich Text Editor (for WYSIWYG)
  # Proven stable version compatible with Dart 3
  flutter_quill: ^11.0.0
  flutter_quill_extensions: ^11.0.0

  # Data storage
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # File management
  file_picker: ^8.1.2
  open_filex: ^4.5.0

  # Preferences (optional untuk pengaturan warna tema, dsb)
  shared_preferences: ^2.2.3

  # Localization
  easy_localization: ^3.0.3

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.3
  permission_handler: ^11.3.1

  # Icon generator
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - lang/
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  # adaptive_icon_background: "#FFFFFF"
  # adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
