name: Flutter Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      confirm:
        description: "Apakah ingin menjalankan workflow ini?"
        required: true
        default: "no"

jobs:
  build:
    if: ${{ github.event.inputs.confirm == 'yes' || github.event_name == 'release' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build Universal APK
        run: flutter build apk --release

      - name: Upload APK to GitHub Release
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
